# Generated by Django 4.1.5 on 2023-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_alter_video_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="run_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
