# Generated by Django 4.1.5 on 2023-03-13 04:00

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        ("videos", "0008_rename_run_time_video_run_time_seconds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="series",
            old_name="overview",
            new_name="plot",
        ),
        migrations.RemoveField(
            model_name="series",
            name="tagline",
        ),
        migrations.AddField(
            model_name="series",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/series/"
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="genres",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="imdb_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="imdb_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/series/"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="imdb_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="plot",
            field=models.TextField(blank=True, null=True),
        ),
    ]
