# Generated by Django 4.1.5 on 2023-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videos",
            "0009_rename_overview_series_plot_remove_series_tagline_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="series",
            old_name="genres",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="video",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/video/"
            ),
        ),
    ]
