# Generated by Django 4.1.5 on 2023-03-14 19:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        ("videos", "0010_rename_genres_series_tags_alter_video_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
