# Generated by Django 4.1.5 on 2023-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_video_next_imdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="preferred_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
