# Generated by Django 4.2.15 on 2024-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0015_alter_video_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="tmdb_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
