# Generated by Django 4.2.15 on 2024-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0016_video_tmdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("E", "TV Episode"),
                    ("M", "Movie"),
                    ("S", "Skate Video"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
