# Generated by Django 4.2.16 on 2024-11-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0017_alter_video_video_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("E", "TV Episode"),
                    ("M", "Movie"),
                    ("S", "Skate Video"),
                    ("Y", "YouTube Video"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
