# Generated by Django 4.2.16 on 2024-11-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videos",
            "0019_rename_youtube_url_video_youtube_id_channel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
