# Generated by Django 4.2.16 on 2025-01-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0020_channel_youtube_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="upload_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
