# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0021_video_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
