# Generated by Django 4.1.5 on 2023-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0008_sportevent_thesportsdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="default_event_type",
            field=models.CharField(
                choices=[
                    ("UK", "Event"),
                    ("GA", "Game"),
                    ("RA", "Race"),
                    ("MA", "Match"),
                ],
                default="UK",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="sportevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("UK", "Event"),
                    ("GA", "Game"),
                    ("RA", "Race"),
                    ("MA", "Match"),
                ],
                default="UK",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="sportevent",
            name="run_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
