# Generated by Django 4.1.5 on 2023-03-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0009_alter_sport_default_event_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sportevent",
            old_name="run_time",
            new_name="run_time_seconds",
        ),
    ]
