# Generated by Django 4.1.5 on 2023-03-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0011_remove_sport_default_event_run_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="default_event_run_time_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
