# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0014_alter_sportevent_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sportevent",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
