# Generated by Django 4.2.16 on 2024-11-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='default_activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
