# Generated by Django 4.2.16 on 2024-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_trail_default_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='principal_type',
            field=models.CharField(blank=True, choices=[('WOODS', 'Woods'), ('ROAD', 'Road'), ('BEACH', 'Beach'), ('MOUNTAIN', 'Mountain')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='default_activity_type',
            field=models.CharField(blank=True, choices=[('WALK', 'Walk'), ('HIKE', 'Hike'), ('RUN', 'Run'), ('BIKE', 'Bike')], max_length=10, null=True),
        ),
    ]
