# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails", "0003_trail_principal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trail",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
