# Generated by Django 4.2.13 on 2024-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="moods/"),
        ),
    ]
