# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0002_mood_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
