# Generated by Django 4.1.5 on 2023-03-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_userprofile_twitch_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="twitch_client_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitch_client_secret",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitch_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitch_token_expires",
        ),
    ]
