# Generated by Django 4.1.5 on 2023-03-22 22:26

from django.db import migrations, models
from profiles.constants import PRETTY_TIMEZONE_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_userprofile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                choices=PRETTY_TIMEZONE_CHOICES,
                max_length=255,
                null=True,
            ),
        ),
    ]
