# Generated by Django 4.1.7 on 2023-04-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="lastfm_auto_import",
            field=models.BooleanField(default=False),
        ),
    ]
