# Generated by Django 4.1.7 on 2023-05-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_userprofile_lastfm_auto_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="retroarch_auto_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="retroarch_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
