# Generated by Django 4.1.7 on 2023-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_userprofile_retroarch_auto_import_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="redirect_to_webpage",
            field=models.BooleanField(default=True),
        ),
    ]
