# Generated by Django 4.2.16 on 2024-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_userprofile_todoist_auth_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="todoist_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
