# Generated by Django 4.2.16 on 2024-10-20 20:04

from django.db import migrations, models
import encrypted_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_userprofile_todoist_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="webdav_auto_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webdav_pass",
            field=encrypted_field.fields.EncryptedField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webdav_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webdav_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
