# Generated by Django 4.2.18 on 2025-01-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0020_userprofile_ntfy_enabled_userprofile_ntfy_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="lichess_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
