# Generated by Django 4.1.5 on 2023-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogame",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
