# Generated by Django 4.1.5 on 2023-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videogames",
            "0003_videogameplatform_videogame_completionist_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogame",
            name="alternative_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="videogame",
            name="platform",
        ),
        migrations.AddField(
            model_name="videogame",
            name="platform",
            field=models.ManyToManyField(
                blank=True, null=True, to="videogames.videogameplatform"
            ),
        ),
    ]
