# Generated by Django 4.1.5 on 2023-03-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames", "0005_rename_platform_videogame_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogame",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="videogame",
            name="platforms",
            field=models.ManyToManyField(to="videogames.videogameplatform"),
        ),
    ]
