# Generated by Django 4.1.5 on 2023-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames", "0006_videogame_summary_alter_videogame_platforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogame",
            name="run_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
