# Generated by Django 4.1.7 on 2023-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videogames", "0010_alter_videogame_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogame",
            name="retroarch_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
