# Generated by Django 4.2.16 on 2024-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="source_url_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Shortcut", "https://app.shortcut.com/sure/story/{id}"),
                    ("Todoist", "https://app.todoist.com/app/task/{id}"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
