# Generated by Django 4.2.16 on 2024-10-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_source_task_source_url_pattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="source",
        ),
        migrations.RemoveField(
            model_name="task",
            name="source_url_pattern",
        ),
    ]
