# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_source_remove_task_source_url_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
