# Generated by Django 4.2.16 on 2024-10-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="beeradvocate_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="beers/beeradvcoate/"
            ),
        ),
        migrations.AddField(
            model_name="beer",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="beers.beerproducer",
            ),
        ),
        migrations.AddField(
            model_name="beerproducer",
            name="beeradvocate_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
