# Generated by Django 4.2.16 on 2024-10-22 21:47

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0002_beer_beeradvocate_image_beer_producer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeerStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="beer",
            name="beeradvocate_image",
        ),
        migrations.RemoveField(
            model_name="beer",
            name="style",
        ),
        migrations.AddField(
            model_name="beer",
            name="untappd_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="beers/untappd/"
            ),
        ),
        migrations.AddField(
            model_name="beer",
            name="untappd_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beerproducer",
            name="untappd_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="beer",
            name="styles",
            field=models.ManyToManyField(to="beers.beerstyle"),
        ),
    ]
