# Generated by Django 4.2.16 on 2024-10-22 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0003_beerstyle_remove_beer_beeradvocate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beerproducer",
            name="name",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beerproducer",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="beerstyle",
            name="name",
            field=models.CharField(default="Untitled", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beerstyle",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="beer",
            name="styles",
            field=models.ManyToManyField(
                related_name="styles", to="beers.beerstyle"
            ),
        ),
    ]
