# Generated by Django 4.1.7 on 2023-11-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_rawgeolocation_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawgeolocation",
            options={},
        ),
    ]
