# Generated by Django 4.1.7 on 2023-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_rawgeolocation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawgeolocation",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="geolocation",
            name="truncated_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geolocation",
            name="truncated_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
