# Generated by Django 4.2.9 on 2024-02-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_rawgeolocation_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawGeoLocation",
        ),
    ]
