jellyfin_keys = [
    "ServerId",
    "ServerName",
    "ServerVersion",
    "ServerUrl",
    "NotificationType",
    "Timestamp",
    "UtcTimestamp",
    "Name",
    "Overview",
    "Tagline",
    "ItemId",
    "RunTimeTicks",
    "RunTime",
    "Year",
    "Provider_tmdb",
    "Provider_imdb",
    "Provider_tmdbcollection",
    "Provider_tmdbset",
    "Video_0_Title",
    "Video_0_Type",
    "Video_0_Codec",
    "Video_0_Profile",
    "Video_0_Level",
    "Video_0_Height",
    "Video_0_Width",
    "Video_0_AspectRatio",
    "Video_0_Interlaced",
    "Video_0_FrameRate",
    "Video_0_VideoRange",
    "Video_0_ColorSpace",
    "Video_0_ColorTransfer",
    "Video_0_ColorPrimaries",
    "Video_0_PixelFormat",
    "Video_0_RefFrames",
    "Audio_0_Title",
    "Audio_0_Type",
    "Audio_0_Language",
    "Audio_0_Codec",
    "Audio_0_Channels",
    "Audio_0_Bitrate",
    "Audio_0_SampleRate",
    "Audio_0_Default",
    "Subtitle_0_Title",
    "Subtitle_0_Type",
    "Subtitle_0_Language",
    "Subtitle_0_Codec",
    "Subtitle_0_Default",
    "Subtitle_0_Forced",
    "Subtitle_0_External",
    "Subtitle_1_Title",
    "Subtitle_1_Type",
    "Subtitle_1_Language",
    "Subtitle_1_Codec",
    "Subtitle_1_Default",
    "Subtitle_1_Forced",
    "Subtitle_1_External",
    "Subtitle_2_Title",
    "Subtitle_2_Type",
    "Subtitle_2_Language",
    "Subtitle_2_Codec",
    "Subtitle_2_Default",
    "Subtitle_2_Forced",
    "Subtitle_2_External",
    "PlaybackPositionTicks",
    "PlaybackPosition",
    "MediaSourceId",
    "IsPaused",
    "IsAutomated",
    "DeviceId",
    "DeviceName",
    "ClientName",
    "NotificationUsername",
    "UserId",
]
VARIOUS_ARTIST_DICT = {
    "name": "Various Artists",
    "theaudiodb_id": "113641",
    "musicbrainz_id": "89ad4ac3-39f7-470e-963a-56509c546377",
}

JELLYFIN_POST_KEYS = {
    "ITEM_TYPE": "ItemType",
    "ITEM_ID": "ItemId",
    "RUN_TIME": "RunTime",
    "TRACK_TITLE": "Name",
    "TIMESTAMP": "UtcTimestamp",
    "YEAR": "Year",
    "OVERVIEW": "Overview",
    "TAGLINE": "TAGLINE",
    "PLAYBACK_POSITION_TICKS": "PlaybackPositionTicks",
    "PLAYBACK_POSITION": "PlaybackPosition",
    "ARTIST_MB_ID": "Provider_musicbrainzartist",
    "ALBUM_MB_ID": "Provider_musicbrainzalbum",
    "RELEASEGROUP_MB_ID": "Provider_musicbrainzreleasegroup",
    "TRACK_MB_ID": "Provider_musicbrainztrack",
    "ALBUM_NAME": "Album",
    "ARTIST_NAME": "Artist",
    "STATUS": "Status",
    "SOURCE": "ClientName",
    "VIDEO_TITLE": "Name",
    "IMDB_ID": "Provider_imdb",
    "TMDB_ID": "Provider_tmdb",
}

MOPIDY_POST_KEYS = {
    "ITEM_TYPE": None,
    "RUN_TIME": "run_time",
    "TRACK_TITLE": "name",
    "TIMESTAMP": None,
    "YEAR": None,
    "PLAYBACK_POSITION_TICKS": "playback_time_ticks",
    "ARTIST_MB_ID": "muscibrainz_artist_id",
    "ALBUM_MB_ID": "musicbrainz_album_id",
    "RELEASEGROUP_MB_ID": None,
    "TRACK_MB_ID": "musicbrainz_track_id",
    "ALBUM_NAME": "album",
    "ARTIST_NAME": "artist",
    "STATUS": "status",
}
