# Generated by Django 4.1.7 on 2023-11-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="webpage",
            name="extract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
