# Generated by Django 4.2.9 on 2024-03-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0002_webpage_domain_webpage_extract"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
