# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0004_domain_alter_webpage_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
