# Generated by Django 4.1.5 on 2023-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0014_album_theaudiodb_year_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="run_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
