# Generated by Django 4.1.5 on 2023-03-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_alter_track_run_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="run_time",
            new_name="run_time_seconds",
        ),
    ]
