# Generated by Django 4.1.5 on 2023-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0017_track_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="allmusic_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="allmusic_review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
