# Generated by Django 4.1.5 on 2023-03-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_album_allmusic_rating_album_allmusic_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="allmusic_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
