# Generated by Django 4.1.5 on 2023-03-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0019_artist_allmusic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="bandcamp_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="bandcamp_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
