# Generated by Django 4.1.5 on 2023-03-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0020_album_bandcamp_id_artist_bandcamp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="albums",
                to="music.artist",
            ),
        ),
    ]
