# Generated by Django 4.1.5 on 2023-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0021_album_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="theaudiodb_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
