# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0023_alter_track_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
