# Generated by Django 4.1.5 on 2023-03-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_author_name_book_author_openlibrary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/covers/"
            ),
        ),
    ]
