# Generated by Django 4.1.5 on 2023-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_author_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="duration_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
