# Generated by Django 4.1.5 on 2023-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books",
            "0007_author_amazon_id_author_bio_author_goodreads_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="first_sentence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
