# Generated by Django 4.1.5 on 2023-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_book_first_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="run_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
