# Generated by Django 4.1.7 on 2023-03-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
