# Generated by Django 4.1.7 on 2023-04-18 02:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0040_alter_scrobble_media_type"),
        ("books", "0013_page_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="scrobbles.ObjectWithGenres",
                to="scrobbles.Genre",
                verbose_name="Tags",
            ),
        ),
    ]
