# Generated by Django 4.1.7 on 2023-08-19 02:47

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0043_scrobbledpage"),
        ("books", "0014_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="first_sentence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="scrobbles.ObjectWithGenres",
                to="scrobbles.Genre",
                verbose_name="Tags",
            ),
        ),
    ]
