# Generated by Django 4.1.7 on 2023-08-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_alter_book_first_sentence_alter_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="locg_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
