# Generated by Django 4.1.7 on 2023-08-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_alter_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="locg_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
