# Generated by Django 4.2.9 on 2024-01-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_alter_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="comicvine_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="comicvine_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="koreader_data_by_hash",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
