# Generated by Django 4.2.16 on 2024-10-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_author_comicvine_data_book_comicvine_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="koreader_authors",
        ),
        migrations.RemoveField(
            model_name="book",
            name="koreader_id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="koreader_md5",
        ),
    ]
