# Generated by Django 4.2.16 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books",
            "0021_remove_book_koreader_authors_remove_book_koreader_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="run_time_seconds",
            field=models.IntegerField(default=900),
        ),
    ]
