# Generated by Django 4.2.18 on 2025-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0022_alter_book_run_time_seconds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="isbn",
            new_name="isbn_13",
        ),
        migrations.RemoveField(
            model_name="book",
            name="comicvine_data",
        ),
        migrations.RemoveField(
            model_name="book",
            name="goodreads_id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="locg_slug",
        ),
        migrations.AddField(
            model_name="book",
            name="isbn_10",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
