# Generated by Django 4.2.18 on 2025-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books",
            "0023_rename_isbn_book_isbn_13_remove_book_comicvine_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
