# Generated by Django 4.1.5 on 2023-03-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0024_chartrecord_period_end_chartrecord_period_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="long_play_complete",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrobble",
            name="videogame_minutes_played",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
