# Generated by Django 4.1.5 on 2023-03-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videogames", "0001_initial"),
        ("scrobbles", "0025_scrobble_long_play_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="video_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="videogames.videogame",
            ),
        ),
    ]
