# Generated by Django 4.1.5 on 2023-03-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0026_scrobble_video_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrobble",
            name="videogame_minutes_played",
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="playback_position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
