# Generated by Django 4.1.5 on 2023-03-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scrobbles",
            "0027_remove_scrobble_videogame_minutes_played_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="video_game_minutes_played",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
