# Generated by Django 4.1.5 on 2023-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0028_scrobble_video_game_minutes_played"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrobble",
            name="video_game_minutes_played",
        ),
        migrations.AddField(
            model_name="scrobble",
            name="long_play_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
