# Generated by Django 4.1.5 on 2023-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scrobbles",
            "0029_remove_scrobble_video_game_minutes_played_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
