# Generated by Django 4.1.5 on 2023-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0030_scrobble_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="playback_position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
