# Generated by Django 4.1.5 on 2023-03-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0031_alter_scrobble_playback_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scrobble",
            old_name="playback_position",
            new_name="playback_position_seconds",
        ),
    ]
