# Generated by Django 4.1.5 on 2023-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0033_genre_objectwithgenres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartrecord",
            name="rank",
            field=models.IntegerField(db_index=True),
        ),
    ]
