# Generated by Django 4.1.7 on 2023-04-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0034_alter_chartrecord_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="videogame_save_data",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="scrobbles/videogame_save_data/",
            ),
        ),
    ]
