# Generated by Django 4.1.7 on 2023-04-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0035_scrobble_videogame_save_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="stop_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
