# Generated by Django 4.1.7 on 2023-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0036_scrobble_stop_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("PodcastEpisode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
