# Generated by Django 4.1.7 on 2023-04-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0001_initial"),
        ("scrobbles", "0038_alter_objectwithgenres_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="board_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="boardgames.boardgame",
            ),
        ),
    ]
