# Generated by Django 4.1.7 on 2023-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0039_scrobble_board_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("Episode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                    ("BoardGame", "Board game"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
