# Generated by Django 4.1.7 on 2023-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0041_retroarchimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="videogame_screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="scrobbles/videogame_screenshot/",
            ),
        ),
    ]
