# Generated by Django 4.2.9 on 2024-01-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0045_scrobble_webpage_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="book_page_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chartrecord",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
