# Generated by Django 4.2.9 on 2024-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0046_scrobble_book_page_data_alter_chartrecord_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="book_koreader_hash",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
