# Generated by Django 4.2.9 on 2024-02-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0048_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scrobble",
            old_name="webpage",
            new_name="web_page",
        ),
    ]
