# Generated by Django 4.2.9 on 2024-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0050_delete_scrobbledpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="scrobble_log",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
