# Generated by Django 4.2.9 on 2024-04-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0052_alter_scrobble_scroble_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrobble",
            name="source_id",
        ),
    ]
