# Generated by Django 4.2.9 on 2024-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0053_remove_scrobble_source_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrobble",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="scrobble",
            name="playback_position_ticks",
        ),
    ]
