# Generated by Django 4.2.11 on 2024-05-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0054_remove_scrobble_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scrobble",
            old_name="scrobble_log",
            new_name="log",
        ),
    ]
