# Generated by Django 4.2.13 on 2024-08-10 20:01

from django.db import migrations, models
import django.db.models.deletion
import scrobbles.dataclasses


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
        ("scrobbles", "0056_scrobble_life_event_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="mood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moods.mood",
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="log",
            field=models.JSONField(
                blank=True,
                decoder=scrobbles.dataclasses.ScrobbleLogDataDecoder,
                encoder=scrobbles.dataclasses.ScrobbleLogDataEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("PodcastEpisode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                    ("BoardGame", "Board game"),
                    ("GeoLocation", "GeoLocation"),
                    ("WebPage", "Web Page"),
                    ("LifeEvent", "Life event"),
                    ("Mood", "Mood"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
