# Generated by Django 4.2.13 on 2024-08-06 15:27

from django.db import migrations, models
import scrobbles.dataclasses


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0056_scrobble_life_event_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="log",
            field=models.JSONField(
                blank=True,
                decoder=scrobbles.dataclasses.ScrobbleMetadataDecoder,
                encoder=scrobbles.dataclasses.ScrobbleMetadataEncoder,
                null=True,
            ),
        ),
    ]
