# Generated by Django 4.2.13 on 2024-08-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0057_alter_scrobble_log"),
        ("scrobbles", "0057_scrobble_mood_alter_scrobble_log_and_more"),
    ]

    operations = []
