# Generated by Django 4.2.15 on 2024-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0058_merge_20240810_2234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrobble",
            name="book_koreader_hash",
        ),
        migrations.RemoveField(
            model_name="scrobble",
            name="book_page_data",
        ),
        migrations.RemoveField(
            model_name="scrobble",
            name="book_pages_read",
        ),
        migrations.RemoveField(
            model_name="scrobble",
            name="videogame_screenshot",
        ),
        migrations.AddField(
            model_name="scrobble",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="scrobbles/videogame_screenshot/",
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="videogame_save_data",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="scrobbles/videogame_save_data/",
            ),
        ),
    ]
