# Generated by Django 4.2.15 on 2024-09-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bricksets", "0001_initial"),
        ("scrobbles", "0059_remove_scrobble_book_koreader_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="brickset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bricksets.brickset",
            ),
        ),
    ]
