# Generated by Django 4.2.15 on 2024-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0060_scrobble_brickset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("PodcastEpisode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                    ("BoardGame", "Board game"),
                    ("GeoLocation", "GeoLocation"),
                    ("WebPage", "Web Page"),
                    ("LifeEvent", "Life event"),
                    ("Mood", "Mood"),
                    ("BrickSet", "Brick set"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
