# Generated by Django 4.2.16 on 2024-09-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trails", "0001_initial"),
        ("scrobbles", "0061_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="trail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trails.trail",
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("PodcastEpisode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                    ("BoardGame", "Board game"),
                    ("GeoLocation", "GeoLocation"),
                    ("Trail", "Trail"),
                    ("WebPage", "Web Page"),
                    ("LifeEvent", "Life event"),
                    ("Mood", "Mood"),
                    ("BrickSet", "Brick set"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
