# Generated by Django 4.2.16 on 2024-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0062_scrobble_trail_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="gpx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="scrobbles/gpx_file/"
            ),
        ),
    ]
