# Generated by Django 4.2.16 on 2024-10-15 18:47

from django.db import migrations, models
import scrobbles.dataclasses


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0064_scrobble_task_alter_scrobble_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrobble",
            name="log",
            field=models.JSONField(
                blank=True,
                decoder=scrobbles.dataclasses.ScrobbleLogDataDecoder,
                default=dict,
                encoder=scrobbles.dataclasses.ScrobbleLogDataEncoder,
                null=True,
            ),
        ),
    ]
