# Generated by Django 4.2.16 on 2024-10-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0001_initial"),
        ("scrobbles", "0065_alter_scrobble_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrobble",
            name="beer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="beers.beer",
            ),
        ),
        migrations.AlterField(
            model_name="scrobble",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Track", "Track"),
                    ("PodcastEpisode", "Podcast episode"),
                    ("SportEvent", "Sport event"),
                    ("Book", "Book"),
                    ("VideoGame", "Video game"),
                    ("BoardGame", "Board game"),
                    ("GeoLocation", "GeoLocation"),
                    ("Trail", "Trail"),
                    ("Beer", "Beer"),
                    ("Task", "Task"),
                    ("WebPage", "Web Page"),
                    ("LifeEvent", "Life event"),
                    ("Mood", "Mood"),
                    ("BrickSet", "Brick set"),
                ],
                default="Video",
                max_length=14,
            ),
        ),
    ]
