# Generated by Django 4.1.7 on 2023-04-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0002_boardgame_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardgame",
            old_name="recommened_age",
            new_name="recommended_age",
        ),
    ]
