# Generated by Django 4.1.7 on 2023-04-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0003_rename_recommened_age_boardgame_recommended_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="seconds_to_play",
        ),
    ]
