# Generated by Django 4.1.7 on 2023-04-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0004_remove_boardgame_seconds_to_play"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardgame",
            name="summary",
        ),
    ]
