# Generated by Django 4.1.5 on 2023-03-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_alter_episode_run_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="run_time",
            new_name="run_time_seconds",
        ),
    ]
