# Generated by Django 4.1.5 on 2023-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0008_episode_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="pdocasts/covers/"
            ),
        ),
    ]
