# Generated by Django 4.1.5 on 2023-03-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_podcast_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="cover",
        ),
        migrations.AddField(
            model_name="podcast",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="podcasts/covers/"
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
