# Generated by Django 4.1.5 on 2023-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0010_remove_podcast_cover_podcast_cover_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="url",
            new_name="feed_url",
        ),
        migrations.AddField(
            model_name="podcast",
            name="google_podcasts_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
