# Generated by Django 4.2.9 on 2024-02-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrobbles", "0048_alter_scrobble_media_type"),
        ("podcasts", "0012_alter_episode_genre"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Episode",
            new_name="PodcastEpisode",
        ),
    ]
